import { BibleContextType, Segments } from "@/types/bible";
import { ProviderProps } from "@/types/common";
import { createContext, useContext } from "react";

const initialState: BibleContextType = {
  bibleBooks: [
    {
      name: "Genesis",
      chapters: 50,
      order: 1,
      segment: Segments.Old,
      path: "genesis",
    },
    {
      name: "Éxodo",
      chapters: 40,
      order: 2,
      segment: Segments.Old,
      path: "exodus",
    },
    {
      name: "Levítico",
      chapters: 27,
      order: 3,
      segment: Segments.Old,
      path: "leviticus",
    },
    {
      name: "Números",
      chapters: 36,
      order: 4,
      segment: Segments.Old,
      path: "numbers",
    },
    {
      name: "Deuteronomio",
      chapters: 34,
      order: 5,
      segment: Segments.Old,
      path: "deuteronomy",
    },
    {
      name: "Josué",
      chapters: 24,
      order: 6,
      segment: Segments.Old,
      path: "joshua",
    },
    {
      name: "Jueces",
      chapters: 21,
      order: 7,
      segment: Segments.Old,
      path: "judges",
    },
    {
      name: "Primer Libro de Samuel",
      chapters: 31,
      order: 8,
      segment: Segments.Old,
      path: "1-samuel",
    },
    {
      name: "Segundo Libro de Samuel",
      chapters: 24,
      order: 9,
      segment: Segments.Old,
      path: "2-samuel",
    },
    {
      name: "Primer Libro de Reyes",
      chapters: 22,
      order: 10,
      segment: Segments.Old,
      path: "1-kings",
    },
    {
      name: "Segundo Libro de Reyes",
      chapters: 25,
      order: 11,
      segment: Segments.Old,
      path: "2-kings",
    },
    {
      name: "Isaías",
      chapters: 66,
      order: 12,
      segment: Segments.Old,
      path: "isaiah",
    },
    {
      name: "Jeremías",
      chapters: 52,
      order: 13,
      segment: Segments.Old,
      path: "jeremiah",
    },
    {
      name: "Ezequiel",
      chapters: 48,
      order: 14,
      segment: Segments.Old,
      path: "ezekiel",
    },
    {
      name: "Oseas",
      chapters: 14,
      order: 15,
      segment: Segments.Old,
      path: "hosea",
    },
    {
      name: "Joel",
      chapters: 3,
      order: 16,
      segment: Segments.Old,
      path: "joel",
    },
    {
      name: "Amós",
      chapters: 9,
      order: 17,
      segment: Segments.Old,
      path: "amos",
    },
    {
      name: "Abdías",
      chapters: 1,
      order: 18,
      segment: Segments.Old,
      path: "obadiah",
    },
    {
      name: "Jonás",
      chapters: 4,
      order: 19,
      segment: Segments.Old,
      path: "jonah",
    },
    {
      name: "Miqueas",
      chapters: 7,
      order: 20,
      segment: Segments.Old,
      path: "micah",
    },
    {
      name: "Nahúm",
      chapters: 3,
      order: 21,
      segment: Segments.Old,
      path: "nahum",
    },
    {
      name: "Habacuc",
      chapters: 3,
      order: 22,
      segment: Segments.Old,
      path: "habakkuk",
    },
    {
      name: "Sofonías",
      chapters: 3,
      order: 23,
      segment: Segments.Old,
      path: "zephaniah",
    },
    {
      name: "Ageo",
      chapters: 2,
      order: 24,
      segment: Segments.Old,
      path: "haggai",
    },
    {
      name: "Zacarías",
      chapters: 14,
      order: 25,
      segment: Segments.Old,
      path: "zechariah",
    },
    {
      name: "Malaquías",
      chapters: 4,
      order: 26,
      segment: Segments.Old,
      path: "malachi",
    },
    {
      name: "Salmos",
      chapters: 150,
      order: 27,
      segment: Segments.Old,
      path: "psalms",
    },
    {
      name: "Job",
      chapters: 42,
      order: 28,
      segment: Segments.Old,
      path: "job",
    },
    {
      name: "Proverbios",
      chapters: 31,
      order: 29,
      segment: Segments.Old,
      path: "proverbs",
    },
    {
      name: "Rut",
      chapters: 4,
      order: 30,
      segment: Segments.Old,
      path: "ruth",
    },
    {
      name: "Cantar de los Cantares",
      chapters: 8,
      order: 31,
      segment: Segments.Old,
      path: "song-of-solomon",
    },
    {
      name: "Eclesiastés",
      chapters: 12,
      order: 32,
      segment: Segments.Old,
      path: "ecclesiastes",
    },
    {
      name: "Lamentaciones",
      chapters: 5,
      order: 33,
      segment: Segments.Old,
      path: "lamentations",
    },
    {
      name: "Ester",
      chapters: 10,
      order: 34,
      segment: Segments.Old,
      path: "esther",
    },
    {
      name: "Daniel",
      chapters: 12,
      order: 35,
      segment: Segments.Old,
      path: "daniel",
    },
    {
      name: "Primer Libro de Crónicas",
      chapters: 29,
      order: 36,
      segment: Segments.Old,
      path: "1-chronicles",
    },
    {
      name: "Segundo Libro de Crónicas",
      chapters: 36,
      order: 37,
      segment: Segments.Old,
      path: "2-chronicles",
    },
    {
      name: "Esdras",
      chapters: 10,
      order: 38,
      segment: Segments.Old,
      path: "ezra",
    },
    {
      name: "Nehemías",
      chapters: 13,
      order: 39,
      segment: Segments.Old,
      path: "nehemiah",
    },
    {
      name: "Ester Suplementos Griegos",
      chapters: 10,
      order: 40,
      segment: Segments.Old,
      path: "greek-esther",
    },
    {
      name: "Judith",
      chapters: 16,
      order: 41,
      segment: Segments.Old,
      path: "judith",
    },
    {
      name: "Tobías",
      chapters: 14,
      order: 42,
      segment: Segments.Old,
      path: "tobit",
    },
    {
      name: "Primer libro de los Macabeos",
      chapters: 16,
      order: 43,
      segment: Segments.Old,
      path: "1-maccabees",
    },
    {
      name: "Segundo libro de los Macabeos",
      chapters: 15,
      order: 44,
      segment: Segments.Old,
      path: "2-maccabees",
    },
    {
      name: "Sabiduría",
      chapters: 19,
      order: 45,
      segment: Segments.Old,
      path: "wisdom",
    },
    {
      name: "Eclesiástico",
      chapters: 51,
      order: 46,
      segment: Segments.Old,
      path: "sirach",
    },
    {
      name: "Baruc",
      chapters: 6,
      order: 47,
      segment: Segments.Old,
      path: "baruch",
    },
    {
      name: "Carta de Jeremías",
      chapters: 1,
      order: 48,
      segment: Segments.Old,
      path: "letter-of-jeremiah",
    },
    {
      name: "Daniel Suplementos Griegos",
      chapters: 3,
      order: 49,
      segment: Segments.Old,
      path: "greek-daniel",
    },
    {
      name: "Evangelio según San Mateo",
      chapters: 28,
      order: 50,
      segment: Segments.New,
      path: "matthew",
    },
    {
      name: "Evangelio según San Marcos",
      chapters: 16,
      order: 51,
      segment: Segments.New,
      path: "mark",
    },
    {
      name: "Evangelio según San Lucas",
      chapters: 24,
      order: 52,
      segment: Segments.New,
      path: "luke",
    },
    {
      name: "Evangelio según San Juan",
      chapters: 21,
      order: 53,
      segment: Segments.New,
      path: "john",
    },
    {
      name: "Hechos de los Apóstoles",
      chapters: 28,
      order: 54,
      segment: Segments.New,
      path: "acts",
    },
    {
      name: "Carta a los Romanos",
      chapters: 16,
      order: 55,
      segment: Segments.New,
      path: "romans",
    },
    {
      name: "Primera Carta a los Corintios",
      chapters: 16,
      order: 56,
      segment: Segments.New,
      path: "1-corinthians",
    },
    {
      name: "Segunda Carta a los Corintios",
      chapters: 13,
      order: 57,
      segment: Segments.New,
      path: "2-corinthians",
    },
    {
      name: "Carta a los Gálatas",
      chapters: 6,
      order: 58,
      segment: Segments.New,
      path: "galatians",
    },
    {
      name: "Carta a los Efesios",
      chapters: 6,
      order: 59,
      segment: Segments.New,
      path: "ephesians",
    },
    {
      name: "Carta a los Filipenses",
      chapters: 4,
      order: 60,
      segment: Segments.New,
      path: "philippians",
    },
    {
      name: "Carta a los Colosenses",
      chapters: 4,
      order: 61,
      segment: Segments.New,
      path: "colossians",
    },
    {
      name: "Primera Carta a los Tesalonicenses",
      chapters: 5,
      order: 62,
      segment: Segments.New,
      path: "1-thessalonians",
    },
    {
      name: "Segunda Carta a los Tesalonicenses",
      chapters: 3,
      order: 63,
      segment: Segments.New,
      path: "2-thessalonians",
    },
    {
      name: "Primera Carta a Timoteo",
      chapters: 6,
      order: 64,
      segment: Segments.New,
      path: "1-timothy",
    },
    {
      name: "Segunda Carta a Timoteo",
      chapters: 4,
      order: 65,
      segment: Segments.New,
      path: "2-timothy",
    },
    {
      name: "Carta a Tito",
      chapters: 3,
      order: 66,
      segment: Segments.New,
      path: "titus",
    },
    {
      name: "Carta a Filemón",
      chapters: 1,
      order: 67,
      segment: Segments.New,
      path: "philemon",
    },
    {
      name: "Carta a los Hebreos",
      chapters: 13,
      order: 68,
      segment: Segments.New,
      path: "hebrews",
    },
    {
      name: "Carta de Santiago",
      chapters: 5,
      order: 69,
      segment: Segments.New,
      path: "james",
    },
    {
      name: "Primera Carta de San Pedro",
      chapters: 5,
      order: 70,
      segment: Segments.New,
      path: "1-peter",
    },
    {
      name: "Segunda Carta de San Pedro",
      chapters: 3,
      order: 71,
      segment: Segments.New,
      path: "2-peter",
    },
    {
      name: "Primera Carta de San Juan",
      chapters: 5,
      order: 72,
      segment: Segments.New,
      path: "1-john",
    },
    {
      name: "Segunda Carta de San Juan",
      chapters: 1,
      order: 73,
      segment: Segments.New,
      path: "2-john",
    },
    {
      name: "Tercera Carta de San Juan",
      chapters: 1,
      order: 74,
      segment: Segments.New,
      path: "3-john",
    },
    {
      name: "Carta de San Judas",
      chapters: 1,
      order: 75,
      segment: Segments.New,
      path: "jude",
    },
    {
      name: "Apocalipsis",
      chapters: 22,
      order: 76,
      segment: Segments.New,
      path: "revelation",
    },
  ],
};

const BibleContext = createContext<BibleContextType>(initialState);

const BibleProvider = ({ children }: ProviderProps) => {
  return (
    <BibleContext.Provider
      value={{
        bibleBooks: initialState.bibleBooks,
      }}
    >
      {children}
    </BibleContext.Provider>
  );
};

const useBibleContext = () => {
  return useContext(BibleContext);
};

export { BibleContext, BibleProvider, useBibleContext };
