const bibleBooks = [
  { label: "Génesis", value: "genesis" },
  { label: "Éxodo", value: "exodus" },
  { label: "Levítico", value: "leviticus" },
  { label: "Números", value: "numbers" },
  { label: "Deuteronomio", value: "deuteronomy" },
  { label: "Josué", value: "joshua" },
  { label: "Jueces", value: "judges" },
  { label: "Primer Libro de Samuel", value: "1-samuel" },
  { label: "Segundo Libro de Samuel", value: "2-samuel" },
  { label: "Primer Libro de Reyes", value: "1-kings" },
  { label: "Segundo Libro de Reyes", value: "2-kings" },
  { label: "Isaías", value: "isaiah" },
  { label: "Jeremías", value: "jeremiah" },
  { label: "Ezequiel", value: "ezekiel" },
  { label: "Oseas", value: "hosea" },
  { label: "Joel", value: "joel" },
  { label: "Amós", value: "amos" },
  { label: "Abdías", value: "obadiah" },
  { label: "Jonás", value: "jonah" },
  { label: "Miqueas", value: "micah" },
  { label: "Nahúm", value: "nahum" },
  { label: "Habacuc", value: "habakkuk" },
  { label: "Sofonías", value: "zephaniah" },
  { label: "Ageo", value: "haggai" },
  { label: "Zacarías", value: "zechariah" },
  { label: "Malaquías", value: "malachi" },
  { label: "Salmos", value: "psalms" },
  { label: "Job", value: "job" },
  { label: "Proverbios", value: "proverbs" },
  { label: "Rut", value: "ruth" },
  { label: "Cantar de los Cantares", value: "song-of-solomon" },
  { label: "Eclesiastés", value: "ecclesiastes" },
  { label: "Lamentaciones", value: "lamentations" },
  { label: "Ester", value: "esther" },
  { label: "Daniel", value: "daniel" },
  { label: "Primer Libro de Crónicas", value: "1-chronicles" },
  { label: "Segundo Libro de Crónicas", value: "2-chronicles" },
  { label: "Esdras", value: "ezra" },
  { label: "Nehemías", value: "nehemiah" },
  { label: "Ester Suplementos Griegos", value: "greek-esther" },
  { label: "Judith", value: "judith" },
  { label: "Tobías", value: "tobit" },
  { label: "Primer libro de los Macabeos", value: "1-maccabees" },
  { label: "Segundo libro de los Macabeos", value: "2-maccabees" },
  { label: "Sabiduría", value: "wisdom" },
  { label: "Eclesiástico", value: "sirach" },
  { label: "Baruc", value: "baruch" },
  { label: "Carta de Jeremías", value: "letter-of-jeremiah" },
  { label: "Daniel Suplementos Griegos", value: "greek-daniel" },
  { label: "Evangelio según San Mateo", value: "matthew" },
  { label: "Evangelio según San Marcos", value: "mark" },
  { label: "Evangelio según San Lucas", value: "luke" },
  { label: "Evangelio según San Juan", value: "john" },
  { label: "Hechos de los Apóstoles", value: "acts" },
  { label: "Carta a los Romanos", value: "romans" },
  { label: "Primera Carta a los Corintios", value: "1-corinthians" },
  { label: "Segunda Carta a los Corintios", value: "2-corinthians" },
  { label: "Carta a los Gálatas", value: "galatians" },
  { label: "Carta a los Efesios", value: "ephesians" },
  { label: "Carta a los Filipenses", value: "philippians" },
  { label: "Carta a los Colosenses", value: "colossians" },
  { label: "Primera Carta a los Tesalonicenses", value: "1-thessalonians" },
  { label: "Segunda Carta a los Tesalonicenses", value: "2-thessalonians" },
  { label: "Primera Carta a Timoteo", value: "1-timothy" },
  { label: "Segunda Carta a Timoteo", value: "2-timothy" },
  { label: "Carta a Tito", value: "titus" },
  { label: "Carta a Filemón", value: "philemon" },
  { label: "Carta a los Hebreos", value: "hebrews" },
  { label: "Carta de Santiago", value: "james" },
  { label: "Primera Carta de San Pedro", value: "1-peter" },
  { label: "Segunda Carta de San Pedro", value: "2-peter" },
  { label: "Primera Carta de San Juan", value: "1-john" },
  { label: "Segunda Carta de San Juan", value: "2-john" },
  { label: "Tercera Carta de San Juan", value: "3-john" },
  { label: "Carta de San Judas", value: "jude" },
  { label: "Apocalipsis", value: "revelation" },
];
